### ISSUE TITLE
Support Promises for wrapAsyncMethod

### ISSUE THREAD

**Issue by dtothefp** [walmartlabs/easy-fix#2]
Would be nice if `wrapAsyncMethod` supported Promises. Could submit a PR if you're open to it

**Comment by rathbone1200cc** [comment]
I'm open to the idea, as long as we do this without adding much complexity.  See this PR for an attempt (which can be simplified): https://github.com/walmartlabs/easy-fix/pull/4#pullrequestreview-2600873

**Comment by rathbone1200cc** [comment]
Closing, as support for promises are now in master.

**Comment by dtothefp** [comment]
👍
