### ISSUE TITLE
Use easy-fix in a CI env

### ISSUE THREAD

**Issue by mazzy89** [walmartlabs/easy-fix#7]
Which is the approach to use easy-fix in a Continuos Integration env? It's not clear for me at this moment. Which mode should I use to run the integration tests in a CI? Which should be the proper flow? I'm a bit confused

**Comment by rathbone1200cc** [comment]
Typically, you write your tests and run them locally with `TEST_MODE=live`.  When they're working, switch to `TEST_MODE=capture` to capture new mocks.  Often, teams will check in the mocks when they're in good shape.  With the mocks checked in to your repo, you can set up your CI to run tests with `TEST_MODE=replay`.  This works well in CI environments, as replaying the mocks helps tests avoid some of the normal pain points of CI testing - the mocks help cut out state in tests, network latency & private networking issues.
